### PR TITLE
Implement GitHub PR Issue Checker Workflow

### PR DESCRIPTION
**Pull request by smog-root**
**FIX** #418 

**Usage:**

1. When a pull request is created or edited, the workflow automatically triggers.

2. The workflow checks for:
- A non-empty PR description.
- A valid issue reference format (`FIX #<issue-number>` or `FEAT, or DOC #NEW`).
3. If either check fails, the PR will be marked as failing, and the author will receive clear error messages in the PR comments.
4. If all checks pass, a confirmation message will indicate that the PR is valid.

**_Note_**: Kindly add all the labels added to the issue, to this PR!

@YadavAkhileshh

### CODE REVIEW

**Comment by smog-root** [comment]
@YadavAkhileshh Add labels!! I added a Note! can't you read??!

**Comment by smog-root** [comment]
It is not reflected in leaderboard!

**Comment by Meetjain1** [comment]
@smog-root Please dont forget to add labels after merging the pr . As it will create confusion among contributors that their points are not showing up on the leaderboard !

Core Team 
Gssoc-ext

**Comment by smog-root** [comment]
@YadavAkhileshh it's level3 in the issue!! add level3

**Comment by smog-root** [comment]
Why are you not responding? and now you are decreasing the level too???!! make it level3!! NOW!!

**Comment by smog-root** [comment]
Finally you added labels! it was not reflected on my leaderboard!!

Why do you not reply??

**Comment by sanjay-kv** [comment]
@smog-root be polite on the public platform, its quite common PA may forgot to add labels give them some time, and talk nicely. 
also workflow cant be given level3 , level1 is the max as per guidelines.

**Comment by smog-root** [comment]
@sanjay-kv i too have patience. but i contacted him in the mail and his insta and in linedin also!

but he did not gave a single reply!

**Comment by sanjay-kv** [comment]
bring to us the discussion we opened for a reason https://github.com/orgs/GSSoC24/discussions/800

**Pull request merged**
