### PR TITLE
Github actions for more connectivity!

### LINKED ISSUE #465: Github actions for more connectivity!
**We can implement github workflows for the following things:**

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @YadavAkhileshh

_**i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label**_

### PR DESCRIPTION
**Pull request by smog-root**
Closes #465 

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @YadavAkhileshh 

_**Note**_: Add level3 with gssoc-ext and hacktober-accepted labels! assign me to this PR !!

### CODE REVIEW

**Comment by smog-root** [comment]
**Proof**:

**Issue open and close:**

Screenshot 2024-10-21 152058
<br>

**PR raise and  merged:**
Screenshot 2024-10-21 160211

**Comment by smog-root** [comment]
@YadavAkhileshh add level2 with gssoc-ext and hacktoberfeast-accepted labels and merge it!

**Comment by smog-root** [comment]
@MastanSayyad There are 3 workflows added in this PR!! and 1 updated!!
as you told i can get a level2 for it right???

kindly resolve it!

**Comment by MastanSayyad** [comment]
@smog-root looking at your number of workflow Contributions, thay scheme does not apply to you, as I said it is for unique Contributors 

Similar Contributions are okay when done less, if there are more number then need to balance the labels for it

There is someone who building entire web page, someone who contributed for web development or a backend for a website which took more than hours sometimes a day, to them we give level 3, at the same time similar levels to these type of PRs are not fair and worthy whose code is already available in the internet. 

We should do project development through our contributions, but these workflow only benefits repos managements. Its good that you have a great knowledge of github work flows but you should move on to the next too

**Comment by smog-root** [comment]
@MastanSayyad okay. i got you! i will stop working on workflows! and move to real thing!

i have some pending issues on workflows which are assigned to me! i will complete them and move on!! @MastanSayyad

**Pull request merged**
