### PR TITLE
added  welcome login and signup and then playing game

### PR DESCRIPTION
**Pull request by keerthana2-005**
i added  welcome page login page and signup page before playing game 
image
image
image

### CODE REVIEW

**Comment by YadavAkhileshh** [comment]
@keerthana2-005 solve the conflicts

**Comment by keerthana2-005** [comment]
@YadavAkhileshh plz tell what is the conflict while merging

**Comment by YadavAkhileshh** [comment]
@keerthana2-005  index.html,
signup/signup.css,
signup/signup.html this are the conflicting files please solve it

**Comment by keerthana2-005** [comment]
@YadavAkhileshh  plz do check if any issue let me know

**Pull request merged**
