### PR TITLE
Overlapping "How to play" Text

### PR DESCRIPTION
**Pull request by NishantRana07**
there is a slight bug in the code of HTML because "how to play" is twice in the HTML in instruction title ID Div and instructions Div too.

this is how they are overlapping, in my solution, I have Fixed this issue 

Screenshot 2024-10-02 222452

### CODE REVIEW

**Comment by NishantRana07** [comment]
@YadavAkhileshh Have a look Bro

**Comment by NishantRana07** [comment]
@YadavAkhileshh Bro Have a look

**Comment by NishantRana07** [comment]
@YadavAkhileshh Bro have a look

**Comment by NishantRana07** [comment]
> @NishantRana07 please solve the conflicts

Done Brother

**Comment by YadavAkhileshh** [comment]
@NishantRana07 still there is a conflict file

**Pull request closed without merging**
