### PR TITLE
Changed the logo and improved ui/ux (issue resolved:#277)

### PR DESCRIPTION
**Pull request by Iampratyush004**
## What does this PR do?
@YadavAkhileshh 
This PR is set to resolve the required issue i.e. the Change in Logo of website.
Fixes #(issue)

Screenshot 2024-10-13 205310
Screenshot 2024-10-13 205337

## Type of change

- Changed the Logo that has enhanced user experience and shall give user retention.
-Improved the UI/UX

PS: expected tags : gssoc-extd, hacktoberfest-accepted and level 2

### CODE REVIEW

**Comment by Iampratyush004** [comment]
#277 
@YadavAkhileshh

**Comment by YadavAkhileshh** [comment]
@Iampratyush004 please make a better logo

**Comment by Iampratyush004** [comment]
@YadavAkhileshh kindly merge this as the ui/ux is messed up and it became very difficult to commit because now if any minor change occur i have to sync the fork and this work progress might get lost...i will create a new issue and resolve this consequently.
Hope you understand .
Thanks

**Comment by Iampratyush004** [comment]
Adjustment would become easier with this change being reflected in latest

**Comment by Iampratyush004** [comment]
@YadavAkhileshh  I have some more logo sample ready, if i could contact you personally, i would be able to show you and then you may decide on those.
Hope you understand.
Thanks

**Comment by YadavAkhileshh** [comment]
@Iampratyush004 sure

**Pull request merged**
