### PR TITLE
Add trailing dots cursor effect in remaining all pages done ! #748 

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Add trailing dots cursor effect in remaining all pages - #748

https://github.com/user-attachments/assets/7c4cb56f-f36a-4238-9f31-68a744034616

# 📄 Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

# ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have added documentation to explain my changes.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

# 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@YadavAkhileshh

**Comment by Subhajit-2023-44** [comment]
@YadavAkhileshh

**Comment by Subhajit-2023-44** [comment]
@YadavAkhileshh i add it in all page, please give me level 3

**Comment by YadavAkhileshh** [comment]
@Subhajit-2023-44 ok

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 ok

Thank you sir

**Pull request merged**
