### PR TITLE
added a local storage to high score

### LINKED ISSUE #158: No Local Storage in Game and No High Score Feature
#### Description
Currently, the game does not implement local storage, and as a result, all game data is lost when the user refreshes the page. Additionally, there is no concept of a high score. By adding local storage and introducing a high score feature, we can ensure that the game state is preserved, and players can see their best performance across sessions.

#### Steps to Reproduce
1. Play the game and make progress.
2. Refresh the browser window.
3. Notice that all game data is lost.

#### Expected Behavior
- The game should save progress to local storage, so when the user refreshes the page, the game can restore the previous state.
- A high score feature should be added where the user's highest score is stored in local storage and displayed in future sessions.

#### Possible Solution
- Implement local storage to save game data (e.g., player progress, current score, etc.).
- Introduce a high score feature, saving the highest score in local storage and displaying it when the game is reloaded.

#### Screenshot
image

#### Additional Context
Adding local storage and a high score feature will significantly enhance the user experience by preserving progress and providing players with a goal to beat their previous best score.

### PR DESCRIPTION
**Pull request by PATILYASHH**
## What does this PR do?

This PR implements local storage functionality and introduces a high score feature in the game, addressing issue #158. The enhancements allow the game to save the player’s progress and high scores, ensuring that data is retained even after refreshing the page. This not only improves the user experience but also motivates players to achieve better scores across sessions.

### Motivation and Context
The lack of local storage meant that all game data was lost upon refreshing the page. By adding this functionality, players can maintain their progress and see their highest scores, creating a more engaging experience.

### Dependencies
No additional dependencies are required for this change.

### Screenshots
Game Interface

### Video
*Insert link to video demonstrating changes, if available.*

## Type of change

- New feature (non-breaking change which adds functionality)

## How should this be tested?

To test the changes made in this PR:

1. **Play the Game:**
   - Start the game and play to achieve a score.
   
2. **Refresh the Browser:**
   - Refresh the page and verify that the game restores the previous score and lives.

3. **Achieve a New High Score:**
   - Play again to reach a new high score and check if it updates in local storage.

4. **Close and Reopen the Game:**
   - Confirm that the high score persists after closing and reopening the game.

### Tests to Run
- [x] Ensure the game state is preserved after a page refresh.
- [x] Verify that the high score updates correctly after achieving a new score.
- [x] Check that the high score persists after restarting the game.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by YadavAkhileshh** [comment]
@PATILYASHH please solve the conflict and then try to push

**Comment by PATILYASHH** [comment]
@YadavAkhileshh please check the PR

**Comment by YadavAkhileshh** [comment]
@PATILYASHH please solve the conflict and then try to push

**Comment by PATILYASHH** [comment]
image
There is no any conflicts

**Pull request merged**
