### PR TITLE
Update Logo: Remove Background for Improved Aesthetics

### PR DESCRIPTION
**Pull request by shashankgoud18**
This pull request addresses the issue of the website logo appearing awkward due to its visible background. The background has been removed to create a transparent logo that seamlessly integrates with the website's design.

Changes Made:
Updated the logo file to a version with a transparent background.
Ensured that the logo now blends smoothly with the website's overall aesthetic, enhancing the visual appeal.

Screenshot 2024-10-08 165210

### CODE REVIEW

**Comment by YadavAkhileshh** [comment]
@shashankgoud18 make it proper responsive

**Comment by shashankgoud18** [comment]
@YadavAkhileshh As per your suggestion, I've implemented the responsive design adjustments. Please review the changes and let me know if any further improvements are needed.

**Comment by YadavAkhileshh** [comment]
@shashankgoud18 solve the conflict

**Comment by shashankgoud18** [comment]
I’ve resolved the conflict in the PR. Could you please review it once
again

**Comment by YadavAkhileshh** [comment]
@shashankgoud18  conflict is still there so please solve it

**Comment by shashankgoud18** [comment]
@YadavAkhileshh 
Iam solving the conflcts but as you are merging other PR's .The conflicts are raising again.
I have solved the conflicts again. If you are ok with my PR,  merge my PR at first.

**Pull request merged**
