### PR TITLE
Enhanced alignment & styling bugs

### PR DESCRIPTION
**Pull request by Deepak0yadav**
**Before**

Screenshot 2024-10-12 175016

**After**

Screenshot 2024-10-13 015851

### CODE REVIEW

**Comment by Deepak0yadav** [comment]
I have enhanced the positions and styling a lot , so Please merge it under  **label level3**

**Comment by YadavAkhileshh** [comment]
@Deepak0yadav PLEASE SOLVE THE CONFLICT AND THEN TRY TO PUSH THE CODE

**Comment by Deepak0yadav** [comment]
@YadavAkhileshh , Resolved

**Comment by YadavAkhileshh** [comment]
@Deepak0yadav STILL THERE IS A CSS CONFLICT PLEASE SOLVE IT AND THEN TRY TO PUSH

**Comment by Deepak0yadav** [comment]
> @Deepak0yadav STILL THERE IS A CSS CONFLICT PLEASE SOLVE IT AND THEN TRY TO PUSH

Ok

**Comment by Deepak0yadav** [comment]
@YadavAkhileshh , Now is it fine

**Comment by Deepak0yadav** [comment]
@YadavAkhileshh , Thanks

**Pull request merged**
