### PR TITLE
Added pause and resume buttons

### LINKED ISSUE #251: [BUG] Adding pause and resume buttons
### Description

I will add the pause and resume buttons which will be useful

### Screenshots

_No response_

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/YadavAkhileshh/Alien-Invasion-Defense/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by monishkumardvs**
What does this PR do?
This PR introduces functionality for the pause and resume buttons in the Alien Invasion Defense game.

Summary of Changes
Implemented a unified pause/resume button that toggles the game state between paused and active.
The button is positioned between the live score and lives displayed on the game interface for better accessibility.
Added relevant styling to enhance the button's appearance and ensure it fits seamlessly within the game's UI.
Motivation and Context
The addition of pause and resume functionality enhances the user experience by allowing players to take breaks without losing their progress.
Players can now easily pause the game at any time and resume where they left off, making the game more user-friendly.
Dependencies
No new dependencies are required for this change.
Ensure that existing game logic and state management are in place to properly handle the pause and resume functionality.

Fixes #251 

https://github.com/user-attachments/assets/7519c605-307a-4de0-a0ca-90c61b8e1c02

## Type of change

-
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How should this be tested?

- [ x] Test A
- [x ] Test B

## Mandatory Tasks

- [x ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by monishkumardvs** [comment]
Can u add the labels which were assigned in #251 pls it will be helpful to me thank you

**Comment by monishkumardvs** [comment]
can u pls add the gssoc labels pls

**Comment by monishkumardvs** [comment]
Can u review the pr pls

**Comment by YadavAkhileshh** [comment]
@monishkumardvs please solve the conflicts

**Comment by monishkumardvs** [comment]
can u now review the pr pls and addd the labels please ..all conflicts are resolved thank you

**Comment by monishkumardvs** [comment]
add the gsspc  labels pls

**Pull request merged**
