### PR TITLE
Return to home button added to all pages

### PR DESCRIPTION
**Pull request by Son7c**
# 🛠️ Fixes Issue
Fixes: #599 

# 👨‍💻 Description
Added a button that navigates to home page in all pages
## What does this PR do?

- Briefly describe the feature or bug fix you've implemented.
- Highlight any major changes or added functionality.
- Mention how it enhances the project.

# 📄 Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

# 📷 Screenshots/GIFs (if any)
Screenshot 2024-11-01 122409
Screenshot 2024-11-01 122421
Screenshot 2024-11-01 122435
Screenshot 2024-11-01 122448

# ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have added documentation to explain my changes.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

# 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by Son7c** [comment]
@YadavAkhileshh Please merge this PR with appropriate levels.

**Comment by YadavAkhileshh** [comment]
@Son7c please solve the conflict and then try to push

**Comment by Son7c** [comment]
@YadavAkhileshh Resolved please check now.

**Comment by Son7c** [comment]
@YadavAkhileshh Please merge this PR

**Comment by Son7c** [comment]
@YadavAkhileshh This PR is open since yesterday please merge this PR i had resolved all the conflicts

**Pull request merged**
