### PR TITLE
Added hishScore to localStorage

### PR DESCRIPTION
**Pull request by sairampolisetty**
Hello PA,
    I have successfully added the highscore element to the localstorage. So that whenever we refresh the page the score won't be zero. 

Thank you for assigning this task to me. 
@YadavAkhileshh Reveiw once

### CODE REVIEW

**Comment by sairampolisetty** [comment]
@YadavAkhileshh

**Comment by YadavAkhileshh** [comment]
@sairampolisetty Please resolve the conflict

**Comment by sairampolisetty** [comment]
@YadavAkhileshh  how to resolve the conflict i dont know

**Comment by sairampolisetty** [comment]
@YadavAkhileshh  why the labels are not showing.

**Pull request merged**
