### PR TITLE
Created the contributing.md file

### PR DESCRIPTION
**Pull request by Amulya-B28**
## What does this PR do?

This file is a crucial document in open-source repositories, providing clear guidelines and instructions for anyone interested in contributing to the project. It outlines how contributors can get involved, the contribution process, and the repository's coding standards and rules. 

## Type of change

- This change requires a documentation update

## Mandatory Tasks

- [] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by YadavAkhileshh** [comment]
@Amulya-B28 please solve the conflict and then try to push

**Comment by Amulya-B28** [comment]
I'll resolve the conflict and submit it by today. Thank you.

**Comment by Amulya-B28** [comment]
@YadavAkhileshh I have resolved the conflicts and updated the file. Please review the changes and request you to add the ggsoc-ext tag along with hacktoberfest and level tag.

issue: #140

**Comment by Amulya-B28** [comment]
@YadavAkhileshh can you please add hacktoberfest tag as well. Thank you.

**Pull request merged**
