### PR TITLE
add buttons for mobile version

### PR DESCRIPTION
**Pull request by Karan-Mahato**

### CODE REVIEW

**Comment by Karan-Mahato** [comment]
@YadavAkhileshh , I resolved #50, could you please check this pull request and merge it.
Also please assign level to #50 and close it.

**Comment by YadavAkhileshh** [comment]
@Karan-Mahato please resolve the conflicts

**Comment by Karan-Mahato** [comment]
@YadavAkhileshh, Resolve the conflict

**Comment by YadavAkhileshh** [comment]
@Karan-Mahato solve the conflict. And then try to push.

**Pull request closed without merging**
