### PR TITLE
SignUp and Login Form Updation and Enhancement | #Issue 183

### LINKED ISSUE #183: SignUp page UI issue | Overflow of page in X direction
https://github.com/user-attachments/assets/047b4809-d931-436b-ada8-dc90af90ae67

Signup page overflow in X direction and Sign Up text alignment disturb
Please assign this to me.

### PR DESCRIPTION
**Pull request by Shariq2003**
## What does this PR do?

Updation of SignUp and Login Page Enhancement along with UI fixes of Overlfows in both the pages.

Fixes #183 

https://github.com/user-attachments/assets/f67b9a44-f579-40fe-a7b5-0dfd91e5f70d

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## Mandatory Tasks

- [X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by Shariq2003** [comment]
@YadavAkhileshh please review my PR

**Comment by Shariq2003** [comment]
@YadavAkhileshh please review this PR, this is in pending state since 2 days

**Comment by YadavAkhileshh** [comment]
@Shariq2003 please solve the conflict and then try to push

**Comment by Shariq2003** [comment]
> @Shariq2003 please solve the conflict and then try to push

These conflict emerged at this point of time by merge someone's code, well okay resolving

**Comment by Shariq2003** [comment]
> @Shariq2003 please solve the conflict and then try to push

@YadavAkhileshh you have merge someone's branch that have changes the whole website the main branch is now totally collapse 

SignUp Page
image

Main Page
image

That causes conflicts with other branch/Code

**Comment by Shariq2003** [comment]
@YadavAkhileshh my branch is all set that according to the previous main branch (Without the merging of Code that causes the issues now in the main branch), so you can set the main branch code as per my branch.

**Comment by Shariq2003** [comment]
https://github.com/user-attachments/assets/81eaebe5-b043-4ed9-bf50-505e1218bdda



This is my branch

**Comment by YadavAkhileshh** [comment]
@Shariq2003 please check once there is conflict in some files so solve them and then try to push

**Comment by Shariq2003** [comment]
> @Shariq2003 please check once there is conflict in some files so solve them and then try to push

Sir conflicts are in the main branch

**Comment by Shariq2003** [comment]
> bandicam.2024-10-13.19-40-09-234.mp4 
> This is my branch

See this

**Comment by Shariq2003** [comment]
@YadavAkhileshh you have to hard reset the main branch to remove are issues that are currently in main branch

**Comment by Shariq2003** [comment]
@YadavAkhileshh , this issues level is actually 3, please update the level

**Pull request merged**
