### PR TITLE
Fixed the logo position and changed the live life position for proper…

### PR DESCRIPTION
**Pull request by Anjalis14**
… visibility

## What does this PR do?

Fixes #(issue)

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by Anjalis14** [comment]
@YadavAkhileshh will you plz assign level to this its already submited

**Comment by YadavAkhileshh** [comment]
@Anjalis14 please solve the conflict and then try to push

**Comment by YadavAkhileshh** [comment]
@Anjalis14 please solve the conflict and then try to push

**Comment by Anjalis14** [comment]
@YadavAkhileshh i did this is it ok now

**Comment by Anjalis14** [comment]
@YadavAkhileshh  will you plz tell me the pull request has been accepted or not

**Comment by Anjalis14** [comment]
@YadavAkhileshh thanks

**Pull request merged**
