### PR TITLE
Improve Contributors page done - #681 🟢🟢

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Improve Contributors page done - #681 

Before - 🔴This contributor page doesn't display all contributors. which doesn't look good... This contributors page only displays 30 contributors but your total contributors are 107+

Now - 🟢This contributor page doesn't display all contributors... & Its value are dynamically updating... 

https://github.com/user-attachments/assets/dc344165-cbff-4cda-9d94-24ecda192b0e

# 📄 Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

# ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have added documentation to explain my changes.
## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

# 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@YadavAkhileshh sir done #681

image

sir please merge my pr and please add gssoc-ext label and Level 2

Thank You

**Comment by Subhajit-2023-44** [comment]
@YadavAkhileshh

**Comment by Subhajit-2023-44** [comment]
@YadavAkhileshh

**Comment by YadavAkhileshh** [comment]
@Subhajit-2023-44 lvl 1 Because this issue had already been resolved

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 lvl 1 Because this issue had already been resolved

Ok

**Pull request merged**
